### ISSUE TITLE
SQL error (/k create)

### ISSUE THREAD

**Issue by SamB440** [Sitrica/Kingdoms#4]
**Describe the bug/issue**
SQL data does not get saved. In the reproduction below the following error appears:
`02.12 14:25:39 [Server] WARN org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "REPLACE[*] INTO KINGDOMS (ID,DATA) VALUES(?,?);"; expected "ROLLBACK, REVOKE, RUNSCRIPT, RELEASE"; SQL statement:
02.12 14:25:39 [Server] WARN REPLACE INTO Kingdoms (id,data) VALUES(?,?); [42001-200]
02.12 14:25:39 [Server] WARN at org.h2.message.DbException.getJdbcSQLException(DbException.java:453)
02.12 14:25:39 [Server] WARN at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
02.12 14:25:39 [Server] WARN at org.h2.message.DbException.getSyntaxError(DbException.java:243)
02.12 14:25:39 [Server] WARN at org.h2.command.Parser.getSyntaxError(Parser.java:1053)
02.12 14:25:39 [Server] WARN at org.h2.command.Parser.parsePrepared(Parser.java:1013)
02.12 14:25:39 [Server] WARN at org.h2.command.Parser.parse(Parser.java:843)
02.12 14:25:39 [Server] WARN at org.h2.command.Parser.parse(Parser.java:819)
02.12 14:25:39 [Server] WARN at org.h2.command.Parser.prepareCommand(Parser.java:738)
02.12 14:25:39 [Server] WARN at org.h2.engine.Session.prepareLocal(Session.java:657)
02.12 14:25:39 [Server] WARN at org.h2.engine.Session.prepareCommand(Session.java:595)
02.12 14:25:39 [Server] WARN at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1235)
02.12 14:25:39 [Server] WARN at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
02.12 14:25:39 [Server] WARN at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:352)
02.12 14:25:39 [Server] WARN at com.songoda.kingdoms.database.H2Database.lambda$0(H2Database.java:65)
02.12 14:25:39 [Server] WARN at java.lang.Thread.run(Thread.java:748)`

**To Reproduce**
Run /k create <name>, an error will appear in console (and kingdom does not get saved).

**Versions (please complete the following information):**
 - Spigot/PaperSpigot version: 1.14.4 PaperMC Build 233
 - Plugin version: 2.0.0

**Additional context**
h2 database compiled correctly & database.mv.db exists in plugins/FabledKingdoms

**Comment by TimRambo** [comment]
Ive got the same exact problem + i get the problem when just joining my server.

**Comment by TheLimeGlass** [comment]
Fixed in last commit.
